---
# tasks file for tomcat
- name: installing apt update
  apt: 
    update_cache: true

- name: installing java
  apt:
    name: "{{ java_package }}"
    state: latest 

- name: getting the tomcat package from tomcat server
  get_url:
      url: "{{ tomcat_url }}"
      dest: "{{ destination_folder }}"

- name: Extracting the apache tar file
  unarchive:
      src: "{{ item }}"
      dest: "{{ destination_folder }}"
      remote_src: yes 
  with_items:
    - "{{ destination_folder_path }}"

- name: changing port number using template
  template:
      src: template/server.xml.j2
      dest: "{{ tomcat_server_path }}"

- name: starting tomcat
  shell: "{{ item }}"
  with_items:      
      - nohup "{{ destination_folder }}"apache-tomcat-10.0.27/bin/shutdown.sh 
      - nohup "{{ destination_folder }}"apache-tomcat-10.0.27/bin/startup.sh 
